arch: amd64

language: java

jdk: 
  - oraclejdk13

cache:
  directories:
  - $HOME/.m2

addons:
  sonarcloud:
    organization: "randyrh91"
    token: ${SONAR_TOKEN}

script:
  - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar